### ISSUE TITLE
Mac OS X build issue

### ISSUE THREAD

**Issue by miniupnp** [mikrosk/m68k-atari-mint-build#11]
I'm trying to build on travis-ci OS X : https://travis-ci.org/miniupnp/m68k-atari-mint-build/jobs/187226318
getting close, however I think I found an issue in mintlib Makefiles : 
in mintlib/syscall/Makefile : 
```
gen-syscall0:
	$(MAKE) gen-syscall CC="gcc" CFLAGS="-O -Wall" COMPILE="gcc -O -Wall"

gen-syscall: $(gen_objs)
	$(CC) $(gen_objs) -o $@ -lfl
```

hard coding gcc is problematic as on OS X 10.11 the gcc is a frontend to llvm
It should be CC=$(HOST_CC) or something like that
Also there is an issue as libfl doesn't exist on OS X. it should be -ll instead of -lfl

**Comment by miniupnp** [comment]
about the -lfl issue : http://linux-digest.blogspot.fr/2013/01/using-flex-on-os-x.html

**Comment by mikrosk** [comment]
As long as it doesn't break Linux/native builds, no problem. Is it ready to merge?
