### ISSUE TITLE
Detect fully unpacked and patched sources

### ISSUE THREAD

**Issue by mikrosk** [mikrosk/m68k-atari-mint-build#17]
Right now it's easy to mess up things if one presses CTRL+C during `tar xzf` and/or before `patch`. It should be pretty easy to create an empty file which would pose as a flag. Something like:

```
tar xjf gcc-4.6.4.tar.bz2
touch gcc-4.6.4/.source_ok
cd gcc-4.6.4
cat ../gcc.patch | patch -p1
touch .source_patched

```
or even simpler:

```
tar xjf gcc-4.6.4.tar.bz2
cd gcc-4.6.4
cat ../gcc.patch | patch -p1
touch .source_ok
```

Then we would check in `Makefile` whether the file exists and if not, we'd just delete the whole dir and unpacked/patched it again.

**Comment by mikrosk** [comment]
Partially done in cf7d0c45eaf17eff6a27e8b307886a568568c259.

**Comment by miniupnp** [comment]
I think that's the good way to go
