### ISSUE TITLE
Native travis-ci builds are failing

### ISSUE THREAD

**Issue by mikrosk** [mikrosk/m68k-atari-mint-build#23]
To my surprise, travis vms have trouble compiling native binaries even if it works OK on my machine.

Mac OS X build ends on an warning which is treated as error but Linux build seems to have bigger issues. @miniupnp does it work for you?

**Comment by miniupnp** [comment]
I haven't tested recently

**Comment by mikrosk** [comment]
Just try to pull the tree and do `make all` on your local machine.

**Comment by mikrosk** [comment]
@miniupnp: man, it took three investigations to track this down. Commit b5b31c5817bf24850ccda2cda788c68c838a59a9 split stuff like `cd dir && ./configure && make` into separate `cd dir && ./configure` and `cd dir && make`.

Apparently the `./configure` script doesn't remember all the paths for sub-level ones so they ask for `m68k-atari-mint-gcc` and get either nothing (travis) or a wrong one (if you happen to already have some in your $PATH). Which is, of course, totally disastrous, this would make ColdFire builds totally broken. Release builds!

We broke the very purpose of travis builds, we skipped some binaries and assumed if cross compilation is fine, natives must be fine as well. Shame on us!

**Comment by miniupnp** [comment]
well as I'm not interested in native binaries (and cannot test them) I'm focussing on cross compilers
Commit b5b31c5 does so much things because it is a squash merge !

I don't really understand why export PATH is better. Wouldn't be cleaner to set PATH once and for all in the build.sh script ?

**Comment by mikrosk** [comment]
That PATH thing was an error (too early conclusion). The real culprit is as described above.

And you can't set it once for the whole script -- it needs to be changed depending on the target CPU you're building the compiler for (that is, native compiler; for cross compilers it's useless complication).

**Comment by miniupnp** [comment]
so I don't understand what was the problem

**Comment by mikrosk** [comment]
> Commit b5b31c5 split stuff like cd dir && ./configure && make into separate cd dir && ./configure and cd dir && make.

This split was the problem. :) But I found out as the last thing, before that I thought it's a problem with non-exported PATH, which wasn't.

**Comment by miniupnp** [comment]
OK because I didn't understand why export PATH would change something for only 1 command.
I guess I messed something up in spliting the commands.

**Comment by mikrosk** [comment]
No worries, I didn't mean it as an accusation. It's just an important lesson, if one changes something, everything must be tested.

**Comment by miniupnp** [comment]
I just want to understand what I made wrong, and why
