### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by AdamKlob** [mikrosk/m68k-atari-mint-build#25]
Current scripts fail for me: 

```
touch binutils-2.26-m68000-cross.ok
# target specific patches here
touch gcc-m68k-atari-mint.ok
rm -rf gcc-4.6.4-m68000-cross-preliminary.ok gcc-4.6.4-m68000-cross-preliminary
mkdir -p gcc-4.6.4-m68000-cross-preliminary
ln -sfv . /home/adamk/gnu-tools/m68000/m68k-atari-mint/usr
ln: '/home/adamk/gnu-tools/m68000/m68k-atari-mint/usr/.': cannot overwrite directory
Makefile:226: recipe for target 'gcc-4.6.4-m68000-cross-preliminary.ok' failed
make[1]: *** [gcc-4.6.4-m68000-cross-preliminary.ok] Error 1
make[1]: Leaving directory '/mnt/nas/projekty/m68k-atari-mint-build'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by mikrosk** [comment]
My guess would be that the build has been interrupted and again restarted by you without deleting the target directory.

I want to get back to this and clean this mess for good but until then... `rm -rf ~/gnu-tools` and start again. ;)

If the issue persists, please post your environment so I can try to reproduce.

**Comment by AdamKlob** [comment]
Ok, it works after I deleted rm -rf ~/gnu-tools

Still a bug ;)

**Comment by mikrosk** [comment]
I have much better makefile (which should fix also issues like this) in works (read: "on hold" ;-)) so nah, closing for now.
