### ISSUE TITLE
Builds taking too long on Mac

### ISSUE THREAD

**Issue by miniupnp** [mikrosk/m68k-atari-mint-build#28]
The travis build is failing with the message : 
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
Looks like it is still using clang instead of gcc-4.9

**Comment by miniupnp** [comment]
let see if there is an improvement with 65d139902d0d2032aee50f37043a32be0748e41e

**Comment by miniupnp** [comment]
looks like it is fixed by 06fe4094d0aa1b39016199dc3c40cc76067ec1e2
but building is too slow anyway :(
`The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by mikrosk** [comment]
Yes, this is a problem. One solution would be to have the binaries published somewhere (e.g. bintray) and download them directly; so let's say binutils wouldn't need to build when gcc is building. But that would defy the purpose of this script (and travis verification), i.e. that you can build everything from scratch in one go.

**Comment by miniupnp** [comment]
Or we can optimize to be below the 50 minutes limit ;)

**Comment by miniupnp** [comment]
Note: everything is still fast enough on the gcc-4.6.4 branch :)

**Comment by mikrosk** [comment]
I don't know how to interpret it but yeah, gcc 7.x compiles much longer.

**Comment by mikrosk** [comment]
Just for the record, prolonging a build is possible: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out

However every time I tried to implemented, I couldn't get it working at all. @miniupnp if you feel up to it, a PR is most welcome. :)

**Comment by miniupnp** [comment]
I see a work around for the "no output" timeout of 10 minutes, but nothing for the overall timeout of 50 minutes  or so...

**Comment by mikrosk** [comment]
Hmm, I have hoped that travis_wait would extend also the overall build time. Oh well.
