### ISSUE TITLE
gcc 4.9 on Mac OS X lacks features.h

### ISSUE THREAD

**Issue by mikrosk** [mikrosk/m68k-atari-mint-build#35]
This is somewhat related to #11 - we need to compile a few files in `mintlib` natively and one of the files requires a macro from `features.h` which seems to be lacking on that image? (xcode8)

Any idea @miniupnp what could fix it?

Btw, only recently I have found out that using CC=gcc-49 never really worked. Travis uses a slightly different method in their [example](https://docs.travis-ci.com/user/languages/c/#gcc-on-os-x) and that did the trick.

**Comment by miniupnp** [comment]
I think that XCode is not including gcc  anymore (for a long time)
so we need to install the native gcc with brew...

**Comment by mikrosk** [comment]
No, gcc 4.9 _is_ there (verified it) - we are still using the old (xcode 8) image. What isn't there is the missing file.

**Comment by mikrosk** [comment]
Fixed by https://github.com/freemint/mintlib/commit/24e61701ca37fa86890b5ce15a2329778ffff353
